# Konfiguration der einzelnen ESPs: Je nach MAC-Adresse, welche Aufgaben habe ich
# und welche Peripherie ist mit mir verbunden?
esps:
  cc:50:e3:b6:87:b8:
    name: Kueche

    components:
      exports:
        test2/constant1: 4
        test2/seconds: seconds
        test2/luft: luft
        test2/solldebug: soll
        test2/ids: ids
        test2/temperatures: temperatures

      imports:
        soll: 
          input: a/1/3/soll
          strobe: seconds
      time:
        time:
          second: seconds
          minute: minutes
      ds18x20:
        4-1:
          start_conversion: seconds
          stable: stable
          ids: ids
          temperatures: temperatures
          28ff8e8d83170400: luft
      
