# Konfiguration der einzelnen ESPs: Je nach MAC-Adresse, welche Aufgaben habe ich
# und welche Peripherie ist mit mir verbunden?
esps:
  b4:e6:2d:8f:c8:29:
    name: Test Tim o. Pins
  b4:e6:2d:8f:bc:59:
    te_antriebe:
      A1.1:
        - 4_2
        - 4_3
        - 4_4
    ds18b20: 2_1
    fbh_regler:
      - A1.1
  cc:50:e3:b6:87:b8:
    name: Testboard Beta
    parts:
      assign:
        # A/1/3/luft: ds18x20/28ff8e8d83170400["temperature_c"]
        # A/1/3/vorlauf: ds18x20/28ffd1c5c11604bc["temperature_c"]
        A/1/3/ruecklauf: |
          [
            A/1/3/kreis1,
            A/1/3/kreis2,
            A/1/3/kreis3,
            A/1/3/kreis4,
            A/1/3/kreis5,
          ]
        A/1/3/antrieb_status: |
          [
            A/1/3/heating_level < 0.3,
            A/1/3/heating_level < 0.4,
            A/1/3/heating_level < 0.5,
            A/1/3/heating_level < 0.6,
            A/1/3/heating_level < 0.7,
          ]
      proportional:
        A/1/3/heating_level:
          sensor: A/1/3/luft
          midpoint: 24.1
          spread: 2
      output_pins:
        1-1: A/1/3/antrieb_status[0]
        1-3: A/1/3/antrieb_status[1]
        1-5: A/1/3/antrieb_status[2]
        2-1: A/1/3/antrieb_status[3]
        2-3: A/1/3/antrieb_status[4]
  cc:50:e3:b6:87:dc:
    name: Testboard Alpha

# Mapping der DS18B20-Temperatursensoren auf sprechende Namen.
ds18x20:
  # Seminarraum
  28eef0b71d1601d7: A/1/1/luft
  28ffa3729017050f: A/1/1/kreis1
  28ffd88b83170400: A/1/1/kreis2
  28ff58ae8317043a: A/1/1/kreis3
  28ffc17cb0160305: A/1/1/kreis4
  28ff5abe90170571: A/1/1/kreis5
  28ff9ca790170564: A/1/1/vorlauf

  # Wohnzimmer
  28ff8339c216042d: A/1/2/luft
  28ff3482b0160315: A/1/2/kreis6
  28fff97c90170532: A/1/2/kreis7
  28ff89ba8317049f: A/1/2/kreis8
  28ffd4bd83170460: A/1/2/kreis9
  28ff11dbc11604b3: A/1/2/kreis10
  28ee18c41d160113: A/1/2/vorlauf

  #Küche
  28ff8e8d83170400: A/1/3/luft
  28c5044398ff0091: A/1/3/kreis1
  28fb1a4398080046: A/1/3/kreis2
  28220c43980e005e: A/1/3/kreis3
  28ff810aa7150328: A/1/3/kreis4
  28ff44ab90170516: A/1/3/kreis5
  28ffd1c5c11604bc: A/1/3/vorlauf
