# Konfiguration der einzelnen ESPs: Je nach MAC-Adresse, welche Aufgaben habe ich
# und welche Peripherie ist mit mir verbunden?
esps:
  cc:50:e3:b6:87:b0:
    name: Kolja Test 2
    parts:
      ds18x20:
        0:
          period: 5
          28ffa7aa831704fd: test/temperature

      proportional:
        test/heating_level:
          sensor: A/1/3/luft
          midpoint: A/1/3/soll
          spread: 2

      slow_pwm:
        test/slow_pwm:
          period: 4
          ratio: 0.2

      input_pins:
        test/in1: 5-1
        test/in3: 5-3
        test/in5: 5-5
        test/in7: 5-7

      output_pins:
#        1-1: kolja/slow_pwm
#        1-3: kolja/slow_pwm
#        1-5: kolja/slow_pwm
#        2-1: kolja/slow_pwm
        2-3: floor( A/1/2/luft ) & 1 
        2-5: test/slow_pwm
        2-7: test/in1 | test/in3 | test/in5 | test/in7

  cc:50:e3:b6:03:44:
    name: ToBi
    parts:
      proportional:
        B/1/11/heating_level:
          sensor: B/1/11/luft
          midpoint: B/1/11/soll
          spread: 2
          interval: 60
     
      ds18x20:
        4-1:
          28250a43980f0083: B/1/11/luft
          #room names below are not correct 
          28c5044398ff0091: B/1/11/kreis1
          28fb1a4398080046: B/1/11/kreis2
          28220c43980e005e: B/1/11/kreis3
          28ff810aa7150328: B/1/11/kreis4
          28ff44ab90170516: B/1/11/kreis5
          28ffd1c5c11604bc: B/1/11/vorlauf
      
      slow_pwm:
        B/1/11/heating_pwm:
          period: 240
          ratio: B/1/11/heating_level 

      output_pins:
        1-1: not B/1/11/heating_pwm
        1-3: not B/1/11/heating_pwm
        1-5: not B/1/11/heating_pwm
        2-1: not B/1/11/heating_pwm
        2-3: not B/1/11/heating_pwm
        2-5: not B/1/11/heating_pwm


# configuration der Temperaturanzeige in der App
raeume:
  A/2/3:
    name:       "Bad"
    fbh_kreise: 3 
  A/2/4:
    name:       "Büro"
    fbh_kreise: 2 
  A/1/1:
    name:       "Seminar"
    fbh_kreise: 4
  A/1/2:
    name:       "Wohnen"
    fbh_kreise: 5
  A/1/3:
    name:       "Küche"
    fbh_kreise: 5
  
     
